version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"   # optional, for websockets
    volumes:
      - $HOME/mosquitto/config:/mosquitto/config
      - $HOME/mosquitto/data:/mosquitto/data
      - $HOME/mosquitto/log:/mosquitto/log
    networks:
      - mqtt_net

networks:
  mqtt_net:
    name: mqtt_net
    driver: bridge

