services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /home/micjcameron/node-red/data:/data
